### ISSUE TITLE
Add test for MARC relator codes in @relator to Schematron

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD3#481]
See http://www.loc.gov/marc/relators/relacode.html. I'd include both the code and the term names in the list of permissible values.

**Comment by tcatapano** [comment]
I'll use http://id.loc.gov/vocabulary/relators.rdf. So you'd like to do a test that the value of the relator attribute match the value of a madsrdf:authoritativeLabel *OR*  madsrdf:code?

**Comment by rockivist** [comment]
@tcatapano Yes, that's what I was thinking. But perhaps we should omit this from the schematron. Although the MARC relator codes would be appropriate to use on `@relator`, there is nothing compelling people to do so. I don't want the schematron to be confused for something prescriptive. Perhaps we could include it but have it commented out by default. What do you think?

**Comment by tcatapano** [comment]
I think we should leave this out for now. If we have the time I can develop an optional pattern which can be imported into the primary schematron

**Comment by rockivist** [comment]
@tcatapano I agree. Table it for now.

**Comment by noahgh221** [comment]
Decision made to omit test for MARC relator codes in Schematron. Closing issue.
