### ISSUE TITLE
Create schematron test to restrict quantity values to numbers

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD3#484]
As suggested by @tcatapano. Data type of integer or decimal.

**Comment by noahgh221** [comment]
@fordmadox  , @rockivist , Do either of you know if this issue was intentionally dropped? Was there a decision not to restrict quantity values to numbers?  Just trying to close out some old, old issues.

**Comment by rockivist** [comment]
I think this just got lost in the shuffle as we were tying up loose ends with the Schematron. Is there a chance Terry did this and it's in a dev branch somewhere? If not, I think it's safe to note that it would still be a good idea but then close the issue. If it comes up again later it could be revisited then.

**Comment by tcatapano** [comment]
I don't recall this. I'll check to refresh my memory and get back. Why not keep it open for now?

We *may* have rejected this as being too strict a rule. There's certainly many cases in which quantity values are not integers or decimals.

**Comment by kerstarno** [comment]
Issue review in preparation to upcoming EAD subteam call on 23 September:

@tcatapano - any chance you found anything pointing to this intially having been dropped with good reason?

@karinbredenberg and @fordmadox - provided we kept this open, might it rather be an issue for the Schema subteam?

**Comment by karinbredenberg** [comment]
@kerstarno if the data type is integer or decimal it should not be possible to write something else. So whats needed is to find if there are other elements/attributes that are seen as quantity vales with not data type integer or decimal and when that list is made it can be decided if it needs to be a rule for them. (Or they should perhaps have the data type being correct which means its part of a major revision.)

**Comment by kerstarno** [comment]
EAD team discussed this issue once more during their meeting on 3 December 2019. 

We don't see this to be an urgent community requirement, especially as it has not been requested or followed up for quite some time, and also are not 100% sure as to whether this might be too strict.

We would hence close this issue for the time being, but will be open to re-evaluate if community requests should be received in future.
