### ISSUE TITLE
Add @render to <quote>

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD3#485]
A suggestion from @tcatapano. Just logging the idea - not to be included in the initial version of EAD3.

**Comment by rockivist** [comment]
Implemented in branch issue_#485. Wait for final approval to merge.

**Comment by rockivist** [comment]
@fordmadox Looks good in all six 1.1 release candidate schemas.

**Comment by rockivist** [comment]
@fordmadox Looks good in all six 1.1.2 release candidate schemas.

**Comment by noahgh221** [comment]
@fordmadox  Looks like this was implemented. Closing Issue.

Inspired by meeting this morning to cleanup these issues:)
