### ISSUE TITLE
<part> example error in tag library

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/EAD3#500]
On page 277 of the tag library, the provided example for `<part>` is:

`<persname encodinganalog="600" relator="creator" rules="RDA" source="http://viaf.org/viaf/23746712">`
`<part localtype="surname">Casey</part>`
`<part localtype="givenname">Silas</part>`
`<part localtype="dates">1807-1882</part>`
`</persname>`

The `persname@source` attribute is misused here - the URI should instead be in `persname@identifier`, akin to the `<persname>` Silas Casey example on page 280.

**Comment by rockivist** [comment]
@alexduryee You are right. Great catch. We are still in the process of encoding the Tag Library in TEI, so this issue will make sure we catch it there and we'll feed it back into the print edition next time they produce more.

**Comment by karinbredenberg** [comment]
Fixed in the TEI.
