### ISSUE TITLE
XSD does not allow <languagedeclaration>

### ISSUE THREAD

**Issue by sterkenburgsara** [SAA-SDT/EAD3#502]
XSD Schema missing an allowance for the <languagedeclaration> element.

**Comment by ruthtillman** [comment]
Hi Sara, the file I'm looking at https://github.com/SAA-SDT/EAD3/blob/master/ead3.xsd has `<languagedeclaration>` in the `<control>` section of the layout. The `<control>` section is ordered, however, so it can only be used directly following the required element `<maintenanceagency>`. Does that solve the validation issue? if not, would you be willing to share a snippet or gist of code from your sample that isn't validating?

**Comment by rockivist** [comment]
@sterkenburgsara Thanks for logging the issue. I believe that @ruthtillman is correct in her suspicion that the problem may relate to the sequence of elements within control that is imposed by the schema. I've double checked the XSD and auto-generated a document. languagedeclaration is absolutely included in the schema - it's available zero or more times as an immediate following sibling of maintenanceagency. 

I will keep the issue open until you can confirm that you have gotten languagedeclaration to work in your local instance, however. I'd be happy to take a look at a file if you want to attach one to the issue.

**Comment by sterkenburgsara** [comment]
Ah, you're correct. Sorry to open an unnecessary issue. I for some reason missed that this area had a mandatory ordered sequence. Thanks so much to both of you!

**Comment by rockivist** [comment]
@sterkenburgsara Glad it worked out.
