### ISSUE TITLE
Add @localtype to <conventiondeclaration>

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD3#507]
I propose adding `@localtype` to `<conventiondeclaration>` as an optional attribute. This seems like an oversight on our part - there are many possible ways in which you might want to subclass a convention declaration. For example, you might want to distinguish between content standard declarations from controlled vocabulary/thesauri declarations.

**Comment by ruthtillman** [comment]
Generally a fan of @localtype being available.

**Comment by rockivist** [comment]
Implemented this in the issue_#507 branch. Wait to merge until final approval.

**Comment by rockivist** [comment]
@fordmadox Looks good in all six 1.1 release candidate schemas.

**Comment by rockivist** [comment]
@fordmadox Looks good in all six 1.1.2 release candidate schemas.

**Comment by noahgh221** [comment]
Included in EAD3 v1.1.0 release. Closing issue.
