### ISSUE TITLE
Test EAD3 1.1 release candidate in different XML libraries

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD3#510]
@tcatapano Please test https://github.com/SAA-SDT/EAD3/releases/tag/v1.1.0-beta in the XML libraries where objectxml wasn't working.

**Comment by rockivist** [comment]
@fordmadox What branches did you merge into the branch from which you generated the RC? I ran a diff on the XSD and RNG for EAD3 1.0 and the EAD3 1.1 RC, and I saw no difference between the definitions for objectxmlwrap. 

@tcatapano In which branch did you do that dev work? Can you point Mark at it?

**Comment by fordmadox** [comment]
@rockivist for that particular issue, i merged the https://github.com/SAA-SDT/EAD3/commits/issue_%23499 branch.  in total, i merged 5 branches:  485, 499, 505, 506, 507.

**Comment by tcatapano** [comment]
@rockivist @fordmadox Im looking into it...

**Comment by tcatapano** [comment]
looks as if the problem is with the 499 branch. this commit says I created ead3_step1.xsd, but it doesnt look like the final one got generated: https://github.com/SAA-SDT/EAD3/commit/7f8ef0f579b7869497062e6b2069b2a252f2f620

I'll fix ASAP.

**Comment by fordmadox** [comment]
@tcatapano : please test the objectxmlwrap issues again with this release, https://github.com/SAA-SDT/EAD3/releases/tag/v1.1.0-beta

**Comment by noahgh221** [comment]
Closing this issue. Assuming this testing took place a long time ago before release of v1.1
