### ISSUE TITLE
Change data type for @containerid from NMTOKEN to string so it can accept special characters

### ISSUE THREAD

**Issue by noahgh221** [SAA-SDT/EAD3#512]
Barcode values may contain special characters (e.g. $, %, #).  Currently @containerid only accepts NMTOKEN values, which can't include such special characters.  I propose relaxing the data type for @containerid from NMTOKEN to string to accept special characters.

**Comment by rockivist** [comment]
@noahgh221 Check out ead3.rng in the issue_512 branch. Do your barcodes validate in containerid now?

**Comment by noahgh221** [comment]
Yes! Barcodes with special characters in containerid now validate against this modified schema. Thanks.

**Comment by rockivist** [comment]
Good. I consider this a bug, not a feature request, so I don't think it's something that needs to be vetted with TS-EAS at large. That said I have probably already been removed from that mailing list, so could you send out a heads up to the committee that we have another bug that has been fixed and can be included in the 1.1 release?

I'll issue a pull request.

**Comment by noahgh221** [comment]
Will do. Thanks.

**Comment by fordmadox** [comment]
Fixed by Mike, and this is now available in all 6 versions of the schema (which are still in testing, but should hopefully be in the master branch soon)

**Comment by rockivist** [comment]
@fordmadox Looks good in all six 1.1.2 release candidate schemas.
