### ISSUE TITLE
Revise Tag Library description of rightsdeclaration

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD3#521]
## Creator of issue

1. Mike Rush
2.
3.
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 
I'd like to see the Description and Usage section of the Tag Library entry for rightsdeclaration revised and the example updated. The current usage guidance and example suggest that the citation element should be empty and descriptivenote should be used for any text identifying the license. From my recollection of issue #506 the intended use of citation was both for linking to structured rights statements and (optionally) for encoding the name of the license. Like this: 

` <citation href=”https://creativecommons.org/publicdomain/zero/1.0/”> CC0 1.0 Universal (CC0 1.0) </citation>`

And descriptivenote should be used for any additional explanatory text, not all explanatory text.

## Reporting a bug

* Text:

## Suggested Solution

* Text: 
Here is my suggested revised wording for the usage section:

`<citation> must be used to provide a machine-readable reference to a license statement (for example, a dereferenceable URI). It may also be used to encode the name of the license statement.
<descriptivenote> may be used to provide additional, human-readable description or explanation of the license statement.`

And here is my suggested example (which omits descriptivenote since I don't think there is much reason to recommend its use.)

`<control>
<rightsdeclaration>
<abbr>CC0</abbr>
<citation href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 1.0 Universal (CC0 1.0)</citation>
</rightsdeclaration>
</control>`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by noahgh221** [comment]
@alexduryee , this seems like a reasonable and uncontroversial suggested edit to the EAD3 tag library.  Would you be able to make the change that Mike suggests to the TEI?

Here is the current entry for rightsdeclaration:
https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-rightsdeclaration

**Comment by kerstarno** [comment]
Just as a thought, picking up on the question of how to use `<descriptivenote>`. I'd think, it might be a useful to e.g. add a short text (in this case taken from the "human-readable summary of the Legal Code" as promoted on the Creative Commons website to actually tell users what the licence means for them.

In this case, the example given above could be extended to:
`<control>
   <rightsdeclaration>
      <abbr>`CC0`</abbr>`
      `<citation href="https://creativecommons.org/publicdomain/zero/1.0/">`
      CC0 1.0 Universal (CC0 1.0)`</citation>`
      `<descriptivenote>
         <p>`This work has been dedicated to the public domain, meaning that you can copy, modify, 
         distribute and perform the work, even for commercial purposes, all without asking 
         permission.`</p>
      `</descriptivenote>
   </rightsdeclaration>
</control>

**Comment by rockivist** [comment]
I like Kerstin's suggestion. A definite improvement to the proposed example.

**Comment by alexduryee** [comment]
I filed a pull request for this change - https://github.com/karinbredenberg/EAS-TagLibraries/pull/6 - which uses Mike and Kerstin's language for `rightsdeclaration`.

**Comment by kerstarno** [comment]
Closing this issue as having been dealt with as part of EAD3 1.1.1 (https://github.com/SAA-SDT/EAS-TagLibraries/pull/48)
