### ISSUE TITLE
<c12> not validating in schema

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/EAD3#523]
## Creator of issue

1. Kelly Revak, Library of Congress
2. e-mails: kere@loc.gov; cconr@loc.gov

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Reporting a bug

* Text: Use of the `<c12>` element is not validating against the EAD3 schema. You can  
insert the `<c12>` element, but no child elements can be used.

We looked into the schema (ead3.xsd) and it looks like `<c12>` wasn't defined.  
The other component levels read something like this:

`<xs:complexType name="c11"><xs:complexContent>
        <xs:extension base="m.c.base">
          <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="thead" type="thead" minOccurs="0"/>
            <xs:element name="c12" type="c12" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent></xs:complexType>`

But the `<c12>` element is empty:

`<xs:complexType name="c12"/>`

## Suggested Solution

* Text: We did a test and changed the c12 bit in the ead3.xsd to be this:

`<xs:complexType name="c12"><xs:complexContent>
    <xs:extension base="m.c.base">
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="thead" type="thead" minOccurs="0"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent></xs:complexType>`

...And the `<c12>` component in our test EAD3 did validate.

(we are not experts in schema writing so this may be missing something or  
otherwise incorrect. We assumed that it can't contain any further component  
levels, so took out  `<xs:element name="c12" type="c12"  
maxOccurs="unbounded"/>`

## Steps to Reproduce (for bugs)

1. create an EAD3 with a `<c12>` element with content. It will not validate if the ead3 schema is associated.

## Context

* Text: unable to test `<c12>` in LC EAD3 implementation.

## Your Environment can be a clue to a bug

* Version used: Oxygen XML editor 20.1 and EAD3 v 1.1
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by kerstarno** [comment]
In their meeting on 23 September 2019, TS-EAS EAD team decided that this bug should be corrected. Issue is therefore assigned to the leads of the Schema team for next steps.

**Comment by fordmadox** [comment]
Just a note that I've checked into this issue, and it happens due to the "deglobalize.xsl" transformation process.  

@tcatapano :  i plan to set up a test before making any changes, but do you remember exactly why that step was necessary?

**Comment by tcatapano** [comment]
@fordmadox: it's been a while, but per the comment at  https://github.com/SAA-SDT/EAD3/blob/2f4f1d7bfe35ffd171260d8b1177e5bb0616a86f/inprocess/deglobalize/deglobalize.xsl#L14 the main function of the deglobalize.xsl transformation is to wrap definitions of any element not named 'ead' which is a child of  'xsd:schema' in 'xsd:complexType' elements so that they will not be available as root elements. It's basically a cleanup of the result of the trang conversion from rng.

**Comment by fordmadox** [comment]
Thanks, @tcatapano!  I'll keep that in mind when I add a patch for this issue.

**Comment by fordmadox** [comment]
Closing this out since the change has been merged.
